# Generated by Django 4.0.4 on 2022-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_rightnews_time_rightnews_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightnews',
            name='date',
        ),
        migrations.AddField(
            model_name='rightnews',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
