# Generated by Django 4.0.4 on 2022-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_rightnews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightnews',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
