# Generated by Django 4.0.4 on 2022-06-29 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rightnews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightnews',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
