# Generated by Django 4.0.4 on 2022-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_rightnews_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightnews',
            name='date',
        ),
    ]
