# Generated by Django 4.0.4 on 2022-06-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_rightnews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightnews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
