# Generated by Django 4.0.4 on 2022-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightnews',
            name='shorttext',
            field=models.TextField(null=True),
        ),
    ]
